server:
  http_listen_port: 3200
  grpc_listen_port: 9096  # Tempo's internal gRPC

distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318  # OTLP HTTP receiver
        grpc:
          endpoint: 0.0.0.0:4317  # OTLP gRPC receiver (different from internal!)

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks

compactor:
  compaction:
    block_retention: 48h

metrics_generator:
  registry:
    external_labels:
      source: tempo
  storage:
    path: /tmp/tempo/generator