server:
  http_listen_port: 3200
  grpc_listen_port: 0

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks

compactor:
  compaction:
    block_retention: 24h
receiver:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318